# Generated by Django 4.1.3 on 2022-12-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='post',
            name='count_like',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайк'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(auto_created=True, verbose_name='Дата создание'),
        ),
    ]
